### ISSUE TITLE
Use modern syntax

### ISSUE THREAD

**Issue by sayem314** [c0b41/xtorrent#10]
Please take a look at my [fork](https://github.com/sayem314/xtorrent)

- Packages were updated since cheerio and another dependency is over 3yrs old
- ES6 syntax and prettier is being used
- Updated search method
- Improved and faster title parsing
- Tests updated
- Custom 1337x domain support

**Comment by c0b41** [comment]
nice stuff, can you send pull request..

**Comment by sayem314** [comment]
Sure, that’s why I have opened this. But I wanna make few more major changes. Atm uploader property was changed to string to show username only to speed up the performance by a little bit and domain is excluded from the href property since not everyone is using the same domain and this is cleaner as well. Will make PR tomorrow.

The new major change I’m proposing is that we should provide torrents to torrents property instead of returning just array and domain property for returning the domain that was used. What do you think?

**Comment by c0b41** [comment]
hımm, i am okay with this breaking change for the uploader property and torrents array 👍
also i am gonna drop lts node version, so this okay the breaking change, i am wating pull request..

**Comment by sayem314** [comment]
Thanks. I would also like to add itorrents mirror link to the download properly. Will make PR soon. Gotta sleep now.

**Comment by sayem314** [comment]
Created PR. Bum the version to 0.4.x or 1.x and publish to npm :smile:

**Comment by c0b41** [comment]
fixed #11
