### ISSUE TITLE
Titles are being cut-off

### ISSUE THREAD

**Issue by kiriles90** [c0b41/xtorrent#8]
Basically the issue is that `info.title` is getting cut-off because 1337x is cutting it in `<.box-info-heading>`

I couldnt find the full torrent name anywhere in the html other than the `<title>` so.. how about
`info.title =$content('.box-info-heading').text();` becoming
`info.title = $content('title').text().replace('Download ','').replace(' Torrent | 1337x','');`

I know it doesnt look pretty and its at the whim of 1337x if they ever change the title format it will get messed up (they havent in a long time though) but for now it gets the job done.  

P.s I will take no offence in a "no, this sucks.." answer. ..I know this is not an optimal solution.

**Comment by c0b41** [comment]
can you send me some long name example

**Comment by c0b41** [comment]
Fixed https://github.com/c0b41/xtorrent/commit/772134e3e37a05291364d7374e4a2cdbef3556ee

**Comment by c0b41** [comment]
hımm you are right, one the way get title element..

**Comment by sayem314** [comment]
`info.title = $content(".box-info-heading").text().trim()`

Works fine for `xtorrent.info`

**Comment by c0b41** [comment]
Issue fixed, upgrade latest version
